### ISSUE TITLE
이러한 에러명이 나오는데, pip install discord.py해도 적용이 안되요. ㅠㅠ

### ISSUE THREAD

**Issue by Jung-Jun** [J-hoplin1/Papago-API-Translate-Bot#2]
C:\Users\myipo\PycharmProjects\DiscordBot\venv\Scripts\python.exe C:/Users/myipo/PycharmProjects/DiscordBot/venv/Include/PapagoBot.py
Traceback (most recent call last):
  File "C:/Users/myipo/PycharmProjects/DiscordBot/venv/Include/PapagoBot.py", line 6, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

Process finished with exit code 1

------------------------------------------

C:\Users\myipo\PycharmProjects\DiscordBot\venv\Scripts\python.exe C:/Users/myipo/PycharmProjects/DiscordBot/venv/Include/PapagoAPIBasicUsage.py
Traceback (most recent call last):
  File "C:/Users/myipo/PycharmProjects/DiscordBot/venv/Include/PapagoAPIBasicUsage.py", line 30, in <module>
    entData = quote()
TypeError: quote() missing 1 required positional argument: 'string'

Process finished with exit code 1

**Comment by Jung-Jun** [comment]
추가로, https://jhoplin7259.tistory.com/91?category=927506 를 참고했고, 
컴퓨터에서 적용이 되는게 확인된다면 집에 있는 NAS로 실행하려고 합니다.
파이썬을 잘 몰라서 이번에 디코에 추가하려는데 어려움이 있는데, 도와주시면 감사하겠습니다. ㅠㅠ

제가 이해하기론, 1번의 경우에는 pip install discord.py 가 적용이 안된거 같은데, 무슨문제일까요?
2번의 경우는 quote()에 무슨 문제가 있다는 뜻인거 같은데, 잘 모르겠습니다. ㅠㅠ
https://kkamikoon.tistory.com/119 이걸 보면서 최대한 수정해보려고 하는데, 파이썬이 처음이라 어렵네요 ㅠ

**Comment by dongsu8142** [comment]
pip install discord.py 이 아닌 pip install discord로 해보세요

**Comment by J-Hoplin** [comment]
안녕하세요 Jung-Jun님 네이버 파파고 API를 이용한 번역봇을 개발한 Hoplin이라고 합니다. 우선 저의 디스코드 봇에 관심을 가져주신것에 대해 진심으로 감사드립니다. 우선 두가지의 오류 케이스를 적어주셨습니다. 첫번째는 discord모듈이 설치되지 않았다는 오류 내용이 발생하셔서 pip install disord.py 명령어로 discord api설치를 하려 하셨지만 잘 안되었다고 하셨는데, 파이썬의 외부지원 모듈들(discord, django, pandas, numpy등등)을 설치할 때는 pip install (모듈이름) 혹은 pip3 install (모듈이름)으로 설치를 진행해 주셔야 됩니다. 그렇기 때문에 여기서는 pip install discord로 설치를 해주시는게 맞습니다. 두번째로 PapagoAPIBasicUsage.py에서 오류내용을 적어주셨는데,  해당 파이썬 파일은 파파고 API 한영 번역 예제 파일입니다. quote()라는 함수는 비 ASCII로 구성된 텍스트를 인코딩 해주는 함수입니다. 그리고 quote()안에는 번역하실 한글 문장을 적어주셔야 됩니다. 에러 내용을 보시면 TypeError: quote() missing 1 required positional argument: 'string 라고 나와있는데, 이 오류를 해석해 보면 quote()라는 함수는 'string'이라는 최소 하나의 매개변수가 들어와야 되는데, 매개변수가 없다는것을 의미합니다. 해당 예제 파일에 quote에 예시 문장을 넣어두었으니 해당 파일로 다시 실행해 보시기 바랍니다.

**Comment by dongsu8142** [comment]
해결 되셨으면 이슈 닫아주세용

**Comment by Jung-Jun** [comment]
thank you for helping
